import asyncio
from playwright.async_api import async_playwright
URL="http://localhost:8765/"
async def main():
    fouten=[]
    def check(c,m):
        print(("OK   " if c else "FOUT ")+m)
        if not c: fouten.append(m)
    async with async_playwright() as p:
        b=await p.chromium.launch(); ctx=await b.new_context(); page=await ctx.new_page()
        errs=[]; page.on("pageerror", lambda e: errs.append(str(e)))
        page.on("dialog", lambda d: asyncio.ensure_future(d.accept()))
        await page.goto(URL); await page.wait_for_timeout(600)
        await page.evaluate("new Promise(r=>{const t=idb.db.transaction('kv','readwrite').objectStore('kv').clear(); t.onsuccess=r; t.onerror=r;})")
        await page.goto(URL); await page.wait_for_timeout(600)
        check(await page.evaluate("document.getElementById('storageHint').hidden"), "landing: balk verborgen")
        check(await page.evaluate("getComputedStyle(document.getElementById('storageHint')).display === 'none'"), "landing: verborgen balk neemt geen ruimte in (display none, ook met display:flex in de CSS)")
        await page.click("#btnStarter"); await page.wait_for_timeout(800)
        persisted=await page.evaluate("navigator.storage.persisted()")
        hidden=await page.evaluate("document.getElementById('storageHint').hidden")
        check(hidden == persisted, f"na laden: balk zichtbaar precies als niet persistent (persisted={persisted}, hidden={hidden})")
        txt=await page.text_content("#storageHintText")
        check("kept in this browser" in txt and "Save it to a data file" in txt, f"tekst voor niet-fallback: {txt[:90]}…")
        await page.wait_for_timeout(3200)
        check(await page.evaluate("saveData._persistAsked === true"), "persist() eenmalig aangevraagd bij de eerste opslag")
        await page.click("#storageHintClose"); await page.wait_for_timeout(200)
        check(await page.evaluate("document.getElementById('storageHint').hidden"), "sluitknop verbergt de balk")
        check(await page.evaluate("getComputedStyle(document.getElementById('storageHint')).display === 'none'"), "na sluiten: balk echt weg (display none)")
        await page.goto(URL); await page.wait_for_timeout(900)
        check(await page.evaluate("document.getElementById('storageHint').hidden"), "zelfde sessie: blijft verborgen (sessionStorage)")
        # nieuwe browsersessie: balk terug (tenzij persistent)
        await ctx.close(); ctx=await b.new_context(); page=await ctx.new_page()
        page.on("pageerror", lambda e: errs.append(str(e)))
        await page.goto(URL); await page.wait_for_timeout(900)
        # nieuwe context = lege IndexedDB, dus landing; laad starter en kijk
        await page.click("#btnStarter"); await page.wait_for_timeout(800)
        p2=await page.evaluate("navigator.storage.persisted()")
        h2=await page.evaluate("document.getElementById('storageHint').hidden")
        check(h2 == p2, f"nieuwe sessie: balk volgt persisted (persisted={p2}, hidden={h2})")
        # FALLBACK-tekst simuleren
        await page.evaluate("FALLBACK = true; updateStorageHint()"); await page.wait_for_timeout(200)
        txt=await page.text_content("#storageHintText")
        check("stays there between sessions" in txt and "Chrome or Edge" in txt, f"fallback-tekst: {txt[-80:]}")
        # Firefox: nooit persist() vragen en persisted() niet geloven (data verdwijnt toch bij afsluiten)
        FF = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0"
        await ctx.close(); ctx = await b.new_context(user_agent=FF); page = await ctx.new_page()
        page.on("pageerror", lambda e: errs.append(str(e)))
        page.on("dialog", lambda d: asyncio.ensure_future(d.accept()))
        await ctx.add_init_script("delete window.showOpenFilePicker; delete window.showSaveFilePicker; navigator.storage.persist = async () => { window.__persistCalled = true; return true; };")
        await page.goto(URL); await page.wait_for_timeout(600)
        await page.click("#btnStarter"); await page.wait_for_timeout(3400)
        check(await page.evaluate("FIREFOX === true"), "Firefox herkend")
        check(not await page.evaluate("window.__persistCalled === true"), "Firefox: persist() wordt niet gevraagd")
        pf = await page.evaluate("navigator.storage.persisted()")
        check(not await page.evaluate("document.getElementById('storageHint').hidden"), f"Firefox: balk blijft staan, ook als persisted={pf}")
        txt = await page.text_content("#storageHintText")
        check("even after you allow persistent storage" in txt, f"Firefox-staart in de balktekst: {txt[-70:]}")

        # iOS: Add to Home Screen in plaats van een installatieknop, en geen advies over Chrome of Edge
        IOSUA = "Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Mobile/15E148 Safari/604.1"
        await ctx.close(); ctx = await b.new_context(user_agent=IOSUA); page = await ctx.new_page()
        page.on("pageerror", lambda e: errs.append(str(e)))
        page.on("dialog", lambda d: asyncio.ensure_future(d.accept()))
        await ctx.add_init_script("delete window.showOpenFilePicker; delete window.showSaveFilePicker;")
        await page.goto(URL); await page.wait_for_timeout(600)
        check(await page.evaluate("IOS === true && SAFARI_MAC === false"), "iOS herkend, en niet als Mac")
        check(await page.is_visible("#btnInstall") and "Home Screen" in await page.text_content("#btnInstall"), "iOS: startscherm biedt Add to Home Screen…")
        await page.click("#btnStarter"); await page.wait_for_timeout(900)
        txt = await page.text_content("#storageHintText")
        check("iPhone or iPad" in txt and "Chrome or Edge" not in txt, f"iOS-staart zonder Chrome-advies: {txt[-90:]}")
        check(not await page.is_visible("#homeToFile"), "iOS: geen Save to a data file… op de Welcome-pagina")
        check((await page.text_content("#btnBack")).strip() == "\u2039 Formulas", "de terugknop noemt de lijst waar hij heen gaat")

        # REMOTE/HANDLE: balk weg
        await page.evaluate("DEMO=false; updateStorageHint()"); await page.wait_for_timeout(200)
        check(await page.evaluate("document.getElementById('storageHint').hidden"), "buiten DEMO: balk verborgen")
        check(not errs, "geen JavaScript-fouten"+("" if not errs else ": "+errs[0][:150]))
        await b.close()
    print("\n"+("%d probleem(en)"%len(fouten) if fouten else "alles in orde"))
asyncio.run(main())
